# Generated by Django 5.2.7 on 2026-02-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_password_alter_user_contact_alter_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(default=None, editable=False, max_length=9, unique=True),
        ),
    ]
