# Generated by Django 5.2.7 on 2026-01-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageId', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('receiverId', models.CharField(max_length=255)),
                ('senderId', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('retryCount', models.IntegerField(default=0)),
                ('lastTriedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['status', 'timestamp'], name='Messaging_m_status_d29c6f_idx'), models.Index(fields=['receiverId', 'status'], name='Messaging_m_receive_0ec842_idx')],
            },
        ),
    ]
