


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;




ALTER SCHEMA "public" OWNER TO "postgres";


CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Messaging_message" (
    "messageId" "uuid" NOT NULL,
    "content" "text" NOT NULL,
    "mediaUrl" character varying(200),
    "timestamp" timestamp with time zone NOT NULL,
    "status" character varying(10) NOT NULL,
    "retryCount" integer NOT NULL,
    "lastTriedAt" timestamp with time zone,
    "receiverId_id" "uuid",
    "senderId_id" "uuid" NOT NULL,
    "room_id" character varying(16)
);


ALTER TABLE "public"."Messaging_message" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Messaging_room" (
    "roomId" character varying(16) NOT NULL,
    "roomName" character varying(50) NOT NULL,
    "icon" character varying(200),
    "bio" "text",
    "timeCreated" timestamp with time zone NOT NULL,
    "owner_id" "uuid" NOT NULL
);


ALTER TABLE "public"."Messaging_room" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Messaging_roommembership" (
    "id" bigint NOT NULL,
    "room_id" character varying(16) NOT NULL,
    "user_id" "uuid" NOT NULL,
    "role" character varying(10) NOT NULL
);


ALTER TABLE "public"."Messaging_roommembership" OWNER TO "postgres";


ALTER TABLE "public"."Messaging_roommembership" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Messaging_roommembership_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."User_asynkuser" (
    "password" character varying(128) NOT NULL,
    "last_login" timestamp with time zone,
    "is_superuser" boolean NOT NULL,
    "first_name" character varying(150) NOT NULL,
    "last_name" character varying(150) NOT NULL,
    "is_staff" boolean NOT NULL,
    "is_active" boolean NOT NULL,
    "date_joined" timestamp with time zone NOT NULL,
    "id" "uuid" NOT NULL,
    "username" character varying(255) NOT NULL,
    "email" character varying(254) NOT NULL,
    "contact" character varying(9) NOT NULL,
    "createdAt" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."User_asynkuser" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."User_asynkuser_groups" (
    "id" bigint NOT NULL,
    "asynkuser_id" "uuid" NOT NULL,
    "group_id" integer NOT NULL
);


ALTER TABLE "public"."User_asynkuser_groups" OWNER TO "postgres";


ALTER TABLE "public"."User_asynkuser_groups" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."User_asynkuser_groups_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."User_asynkuser_user_permissions" (
    "id" bigint NOT NULL,
    "asynkuser_id" "uuid" NOT NULL,
    "permission_id" integer NOT NULL
);


ALTER TABLE "public"."User_asynkuser_user_permissions" OWNER TO "postgres";


ALTER TABLE "public"."User_asynkuser_user_permissions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."User_asynkuser_user_permissions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."auth_group" (
    "id" integer NOT NULL,
    "name" character varying(150) NOT NULL
);


ALTER TABLE "public"."auth_group" OWNER TO "postgres";


ALTER TABLE "public"."auth_group" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_group_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."auth_group_permissions" (
    "id" bigint NOT NULL,
    "group_id" integer NOT NULL,
    "permission_id" integer NOT NULL
);


ALTER TABLE "public"."auth_group_permissions" OWNER TO "postgres";


ALTER TABLE "public"."auth_group_permissions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_group_permissions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."auth_permission" (
    "id" integer NOT NULL,
    "name" character varying(255) NOT NULL,
    "content_type_id" integer NOT NULL,
    "codename" character varying(100) NOT NULL
);


ALTER TABLE "public"."auth_permission" OWNER TO "postgres";


ALTER TABLE "public"."auth_permission" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_permission_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."django_admin_log" (
    "id" integer NOT NULL,
    "action_time" timestamp with time zone NOT NULL,
    "object_id" "text",
    "object_repr" character varying(200) NOT NULL,
    "action_flag" smallint NOT NULL,
    "change_message" "text" NOT NULL,
    "content_type_id" integer,
    "user_id" "uuid" NOT NULL,
    CONSTRAINT "django_admin_log_action_flag_check" CHECK (("action_flag" >= 0))
);


ALTER TABLE "public"."django_admin_log" OWNER TO "postgres";


ALTER TABLE "public"."django_admin_log" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."django_admin_log_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."django_content_type" (
    "id" integer NOT NULL,
    "app_label" character varying(100) NOT NULL,
    "model" character varying(100) NOT NULL
);


ALTER TABLE "public"."django_content_type" OWNER TO "postgres";


ALTER TABLE "public"."django_content_type" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."django_content_type_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."django_migrations" (
    "id" bigint NOT NULL,
    "app" character varying(255) NOT NULL,
    "name" character varying(255) NOT NULL,
    "applied" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."django_migrations" OWNER TO "postgres";


ALTER TABLE "public"."django_migrations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."django_migrations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."django_q_ormq" (
    "id" integer NOT NULL,
    "key" character varying(100) NOT NULL,
    "payload" "text" NOT NULL,
    "lock" timestamp with time zone
);


ALTER TABLE "public"."django_q_ormq" OWNER TO "postgres";


ALTER TABLE "public"."django_q_ormq" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."django_q_ormq_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."django_q_schedule" (
    "id" integer NOT NULL,
    "func" character varying(256) NOT NULL,
    "hook" character varying(256),
    "args" "text",
    "kwargs" "text",
    "schedule_type" character varying(2) NOT NULL,
    "repeats" integer NOT NULL,
    "next_run" timestamp with time zone,
    "task" character varying(100),
    "name" character varying(100),
    "minutes" smallint,
    "cron" character varying(100),
    "cluster" character varying(100),
    "intended_date_kwarg" character varying(100),
    CONSTRAINT "django_q_schedule_minutes_check" CHECK (("minutes" >= 0))
);


ALTER TABLE "public"."django_q_schedule" OWNER TO "postgres";


ALTER TABLE "public"."django_q_schedule" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."django_q_schedule_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."django_q_task" (
    "name" character varying(100) NOT NULL,
    "func" character varying(256) NOT NULL,
    "hook" character varying(256),
    "args" "text",
    "kwargs" "text",
    "result" "text",
    "started" timestamp with time zone NOT NULL,
    "stopped" timestamp with time zone NOT NULL,
    "success" boolean NOT NULL,
    "id" character varying(32) NOT NULL,
    "group" character varying(100),
    "attempt_count" integer NOT NULL,
    "cluster" character varying(100)
);


ALTER TABLE "public"."django_q_task" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."django_session" (
    "session_key" character varying(40) NOT NULL,
    "session_data" "text" NOT NULL,
    "expire_date" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."django_session" OWNER TO "postgres";


ALTER TABLE ONLY "public"."Messaging_message"
    ADD CONSTRAINT "Messaging_message_pkey" PRIMARY KEY ("messageId");



ALTER TABLE ONLY "public"."Messaging_room"
    ADD CONSTRAINT "Messaging_room_pkey" PRIMARY KEY ("roomId");



ALTER TABLE ONLY "public"."Messaging_roommembership"
    ADD CONSTRAINT "Messaging_roommembership_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Messaging_roommembership"
    ADD CONSTRAINT "Messaging_roommembership_user_id_room_id_c9f9ab94_uniq" UNIQUE ("user_id", "room_id");



ALTER TABLE ONLY "public"."User_asynkuser"
    ADD CONSTRAINT "User_asynkuser_contact_key" UNIQUE ("contact");



ALTER TABLE ONLY "public"."User_asynkuser"
    ADD CONSTRAINT "User_asynkuser_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."User_asynkuser_groups"
    ADD CONSTRAINT "User_asynkuser_groups_asynkuser_id_group_id_6e05dbb3_uniq" UNIQUE ("asynkuser_id", "group_id");



ALTER TABLE ONLY "public"."User_asynkuser_groups"
    ADD CONSTRAINT "User_asynkuser_groups_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."User_asynkuser"
    ADD CONSTRAINT "User_asynkuser_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."User_asynkuser_user_permissions"
    ADD CONSTRAINT "User_asynkuser_user_perm_asynkuser_id_permission__2170a8b2_uniq" UNIQUE ("asynkuser_id", "permission_id");



ALTER TABLE ONLY "public"."User_asynkuser_user_permissions"
    ADD CONSTRAINT "User_asynkuser_user_permissions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."User_asynkuser"
    ADD CONSTRAINT "User_asynkuser_username_key" UNIQUE ("username");



ALTER TABLE ONLY "public"."auth_group"
    ADD CONSTRAINT "auth_group_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."auth_group_permissions"
    ADD CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE ("group_id", "permission_id");



ALTER TABLE ONLY "public"."auth_group_permissions"
    ADD CONSTRAINT "auth_group_permissions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_group"
    ADD CONSTRAINT "auth_group_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_permission"
    ADD CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE ("content_type_id", "codename");



ALTER TABLE ONLY "public"."auth_permission"
    ADD CONSTRAINT "auth_permission_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_admin_log"
    ADD CONSTRAINT "django_admin_log_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_content_type"
    ADD CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE ("app_label", "model");



ALTER TABLE ONLY "public"."django_content_type"
    ADD CONSTRAINT "django_content_type_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_migrations"
    ADD CONSTRAINT "django_migrations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_q_ormq"
    ADD CONSTRAINT "django_q_ormq_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_q_schedule"
    ADD CONSTRAINT "django_q_schedule_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_q_task"
    ADD CONSTRAINT "django_q_task_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_session"
    ADD CONSTRAINT "django_session_pkey" PRIMARY KEY ("session_key");



CREATE INDEX "Messaging_m_receive_293ac3_idx" ON "public"."Messaging_message" USING "btree" ("receiverId_id", "status");



CREATE INDEX "Messaging_m_status_d29c6f_idx" ON "public"."Messaging_message" USING "btree" ("status", "timestamp");



CREATE INDEX "Messaging_message_receiverId_id_040f5456" ON "public"."Messaging_message" USING "btree" ("receiverId_id");



CREATE INDEX "Messaging_message_room_id_bd380049" ON "public"."Messaging_message" USING "btree" ("room_id");



CREATE INDEX "Messaging_message_room_id_bd380049_like" ON "public"."Messaging_message" USING "btree" ("room_id" "varchar_pattern_ops");



CREATE INDEX "Messaging_message_senderId_id_c7007371" ON "public"."Messaging_message" USING "btree" ("senderId_id");



CREATE INDEX "Messaging_room_owner_id_63023c78" ON "public"."Messaging_room" USING "btree" ("owner_id");



CREATE INDEX "Messaging_room_roomId_d10dc708_like" ON "public"."Messaging_room" USING "btree" ("roomId" "varchar_pattern_ops");



CREATE INDEX "Messaging_roommembership_room_id_4d267b95" ON "public"."Messaging_roommembership" USING "btree" ("room_id");



CREATE INDEX "Messaging_roommembership_room_id_4d267b95_like" ON "public"."Messaging_roommembership" USING "btree" ("room_id" "varchar_pattern_ops");



CREATE INDEX "Messaging_roommembership_user_id_41fa1033" ON "public"."Messaging_roommembership" USING "btree" ("user_id");



CREATE INDEX "User_asynkuser_contact_92b9dca0_like" ON "public"."User_asynkuser" USING "btree" ("contact" "varchar_pattern_ops");



CREATE INDEX "User_asynkuser_email_e39dc4cb_like" ON "public"."User_asynkuser" USING "btree" ("email" "varchar_pattern_ops");



CREATE INDEX "User_asynkuser_groups_asynkuser_id_f893e994" ON "public"."User_asynkuser_groups" USING "btree" ("asynkuser_id");



CREATE INDEX "User_asynkuser_groups_group_id_49ffe0de" ON "public"."User_asynkuser_groups" USING "btree" ("group_id");



CREATE INDEX "User_asynkuser_user_permissions_asynkuser_id_302700b7" ON "public"."User_asynkuser_user_permissions" USING "btree" ("asynkuser_id");



CREATE INDEX "User_asynkuser_user_permissions_permission_id_170382b4" ON "public"."User_asynkuser_user_permissions" USING "btree" ("permission_id");



CREATE INDEX "User_asynkuser_username_8a44a4a8_like" ON "public"."User_asynkuser" USING "btree" ("username" "varchar_pattern_ops");



CREATE INDEX "auth_group_name_a6ea08ec_like" ON "public"."auth_group" USING "btree" ("name" "varchar_pattern_ops");



CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "public"."auth_group_permissions" USING "btree" ("group_id");



CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "public"."auth_group_permissions" USING "btree" ("permission_id");



CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "public"."auth_permission" USING "btree" ("content_type_id");



CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "public"."django_admin_log" USING "btree" ("content_type_id");



CREATE INDEX "django_admin_log_user_id_c564eba6" ON "public"."django_admin_log" USING "btree" ("user_id");



CREATE INDEX "django_q_task_id_32882367_like" ON "public"."django_q_task" USING "btree" ("id" "varchar_pattern_ops");



CREATE INDEX "django_session_expire_date_a5c62663" ON "public"."django_session" USING "btree" ("expire_date");



CREATE INDEX "django_session_session_key_c0390e0f_like" ON "public"."django_session" USING "btree" ("session_key" "varchar_pattern_ops");



CREATE INDEX "success_index" ON "public"."django_q_task" USING "btree" ("group", "name", "func") WHERE "success";



ALTER TABLE ONLY "public"."Messaging_message"
    ADD CONSTRAINT "Messaging_message_receiverId_id_040f5456_fk_User_asynkuser_id" FOREIGN KEY ("receiverId_id") REFERENCES "public"."User_asynkuser"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."Messaging_message"
    ADD CONSTRAINT "Messaging_message_room_id_bd380049_fk_Messaging_room_roomId" FOREIGN KEY ("room_id") REFERENCES "public"."Messaging_room"("roomId") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."Messaging_message"
    ADD CONSTRAINT "Messaging_message_senderId_id_c7007371_fk_User_asynkuser_id" FOREIGN KEY ("senderId_id") REFERENCES "public"."User_asynkuser"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."Messaging_room"
    ADD CONSTRAINT "Messaging_room_owner_id_63023c78_fk_User_asynkuser_id" FOREIGN KEY ("owner_id") REFERENCES "public"."User_asynkuser"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."Messaging_roommembership"
    ADD CONSTRAINT "Messaging_roommember_room_id_4d267b95_fk_Messaging" FOREIGN KEY ("room_id") REFERENCES "public"."Messaging_room"("roomId") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."Messaging_roommembership"
    ADD CONSTRAINT "Messaging_roommembership_user_id_41fa1033_fk_User_asynkuser_id" FOREIGN KEY ("user_id") REFERENCES "public"."User_asynkuser"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."User_asynkuser_groups"
    ADD CONSTRAINT "User_asynkuser_group_asynkuser_id_f893e994_fk_User_asyn" FOREIGN KEY ("asynkuser_id") REFERENCES "public"."User_asynkuser"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."User_asynkuser_groups"
    ADD CONSTRAINT "User_asynkuser_groups_group_id_49ffe0de_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."auth_group"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."User_asynkuser_user_permissions"
    ADD CONSTRAINT "User_asynkuser_user__asynkuser_id_302700b7_fk_User_asyn" FOREIGN KEY ("asynkuser_id") REFERENCES "public"."User_asynkuser"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."User_asynkuser_user_permissions"
    ADD CONSTRAINT "User_asynkuser_user__permission_id_170382b4_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "public"."auth_permission"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_group_permissions"
    ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "public"."auth_permission"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_group_permissions"
    ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."auth_group"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_permission"
    ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."django_admin_log"
    ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."django_admin_log"
    ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_User_asynkuser_id" FOREIGN KEY ("user_id") REFERENCES "public"."User_asynkuser"("id") DEFERRABLE INITIALLY DEFERRED;





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


REVOKE USAGE ON SCHEMA "public" FROM PUBLIC;







































































































































































































drop extension if exists "pg_net";

revoke delete on table "public"."Messaging_message" from "anon";

revoke insert on table "public"."Messaging_message" from "anon";

revoke references on table "public"."Messaging_message" from "anon";

revoke select on table "public"."Messaging_message" from "anon";

revoke trigger on table "public"."Messaging_message" from "anon";

revoke truncate on table "public"."Messaging_message" from "anon";

revoke update on table "public"."Messaging_message" from "anon";

revoke delete on table "public"."Messaging_message" from "authenticated";

revoke insert on table "public"."Messaging_message" from "authenticated";

revoke references on table "public"."Messaging_message" from "authenticated";

revoke select on table "public"."Messaging_message" from "authenticated";

revoke trigger on table "public"."Messaging_message" from "authenticated";

revoke truncate on table "public"."Messaging_message" from "authenticated";

revoke update on table "public"."Messaging_message" from "authenticated";

revoke delete on table "public"."Messaging_message" from "service_role";

revoke insert on table "public"."Messaging_message" from "service_role";

revoke references on table "public"."Messaging_message" from "service_role";

revoke select on table "public"."Messaging_message" from "service_role";

revoke trigger on table "public"."Messaging_message" from "service_role";

revoke truncate on table "public"."Messaging_message" from "service_role";

revoke update on table "public"."Messaging_message" from "service_role";

revoke delete on table "public"."Messaging_room" from "anon";

revoke insert on table "public"."Messaging_room" from "anon";

revoke references on table "public"."Messaging_room" from "anon";

revoke select on table "public"."Messaging_room" from "anon";

revoke trigger on table "public"."Messaging_room" from "anon";

revoke truncate on table "public"."Messaging_room" from "anon";

revoke update on table "public"."Messaging_room" from "anon";

revoke delete on table "public"."Messaging_room" from "authenticated";

revoke insert on table "public"."Messaging_room" from "authenticated";

revoke references on table "public"."Messaging_room" from "authenticated";

revoke select on table "public"."Messaging_room" from "authenticated";

revoke trigger on table "public"."Messaging_room" from "authenticated";

revoke truncate on table "public"."Messaging_room" from "authenticated";

revoke update on table "public"."Messaging_room" from "authenticated";

revoke delete on table "public"."Messaging_room" from "service_role";

revoke insert on table "public"."Messaging_room" from "service_role";

revoke references on table "public"."Messaging_room" from "service_role";

revoke select on table "public"."Messaging_room" from "service_role";

revoke trigger on table "public"."Messaging_room" from "service_role";

revoke truncate on table "public"."Messaging_room" from "service_role";

revoke update on table "public"."Messaging_room" from "service_role";

revoke delete on table "public"."Messaging_roommembership" from "anon";

revoke insert on table "public"."Messaging_roommembership" from "anon";

revoke references on table "public"."Messaging_roommembership" from "anon";

revoke select on table "public"."Messaging_roommembership" from "anon";

revoke trigger on table "public"."Messaging_roommembership" from "anon";

revoke truncate on table "public"."Messaging_roommembership" from "anon";

revoke update on table "public"."Messaging_roommembership" from "anon";

revoke delete on table "public"."Messaging_roommembership" from "authenticated";

revoke insert on table "public"."Messaging_roommembership" from "authenticated";

revoke references on table "public"."Messaging_roommembership" from "authenticated";

revoke select on table "public"."Messaging_roommembership" from "authenticated";

revoke trigger on table "public"."Messaging_roommembership" from "authenticated";

revoke truncate on table "public"."Messaging_roommembership" from "authenticated";

revoke update on table "public"."Messaging_roommembership" from "authenticated";

revoke delete on table "public"."Messaging_roommembership" from "service_role";

revoke insert on table "public"."Messaging_roommembership" from "service_role";

revoke references on table "public"."Messaging_roommembership" from "service_role";

revoke select on table "public"."Messaging_roommembership" from "service_role";

revoke trigger on table "public"."Messaging_roommembership" from "service_role";

revoke truncate on table "public"."Messaging_roommembership" from "service_role";

revoke update on table "public"."Messaging_roommembership" from "service_role";

revoke delete on table "public"."User_asynkuser" from "anon";

revoke insert on table "public"."User_asynkuser" from "anon";

revoke references on table "public"."User_asynkuser" from "anon";

revoke select on table "public"."User_asynkuser" from "anon";

revoke trigger on table "public"."User_asynkuser" from "anon";

revoke truncate on table "public"."User_asynkuser" from "anon";

revoke update on table "public"."User_asynkuser" from "anon";

revoke delete on table "public"."User_asynkuser" from "authenticated";

revoke insert on table "public"."User_asynkuser" from "authenticated";

revoke references on table "public"."User_asynkuser" from "authenticated";

revoke select on table "public"."User_asynkuser" from "authenticated";

revoke trigger on table "public"."User_asynkuser" from "authenticated";

revoke truncate on table "public"."User_asynkuser" from "authenticated";

revoke update on table "public"."User_asynkuser" from "authenticated";

revoke delete on table "public"."User_asynkuser" from "service_role";

revoke insert on table "public"."User_asynkuser" from "service_role";

revoke references on table "public"."User_asynkuser" from "service_role";

revoke select on table "public"."User_asynkuser" from "service_role";

revoke trigger on table "public"."User_asynkuser" from "service_role";

revoke truncate on table "public"."User_asynkuser" from "service_role";

revoke update on table "public"."User_asynkuser" from "service_role";

revoke delete on table "public"."User_asynkuser_groups" from "anon";

revoke insert on table "public"."User_asynkuser_groups" from "anon";

revoke references on table "public"."User_asynkuser_groups" from "anon";

revoke select on table "public"."User_asynkuser_groups" from "anon";

revoke trigger on table "public"."User_asynkuser_groups" from "anon";

revoke truncate on table "public"."User_asynkuser_groups" from "anon";

revoke update on table "public"."User_asynkuser_groups" from "anon";

revoke delete on table "public"."User_asynkuser_groups" from "authenticated";

revoke insert on table "public"."User_asynkuser_groups" from "authenticated";

revoke references on table "public"."User_asynkuser_groups" from "authenticated";

revoke select on table "public"."User_asynkuser_groups" from "authenticated";

revoke trigger on table "public"."User_asynkuser_groups" from "authenticated";

revoke truncate on table "public"."User_asynkuser_groups" from "authenticated";

revoke update on table "public"."User_asynkuser_groups" from "authenticated";

revoke delete on table "public"."User_asynkuser_groups" from "service_role";

revoke insert on table "public"."User_asynkuser_groups" from "service_role";

revoke references on table "public"."User_asynkuser_groups" from "service_role";

revoke select on table "public"."User_asynkuser_groups" from "service_role";

revoke trigger on table "public"."User_asynkuser_groups" from "service_role";

revoke truncate on table "public"."User_asynkuser_groups" from "service_role";

revoke update on table "public"."User_asynkuser_groups" from "service_role";

revoke delete on table "public"."User_asynkuser_user_permissions" from "anon";

revoke insert on table "public"."User_asynkuser_user_permissions" from "anon";

revoke references on table "public"."User_asynkuser_user_permissions" from "anon";

revoke select on table "public"."User_asynkuser_user_permissions" from "anon";

revoke trigger on table "public"."User_asynkuser_user_permissions" from "anon";

revoke truncate on table "public"."User_asynkuser_user_permissions" from "anon";

revoke update on table "public"."User_asynkuser_user_permissions" from "anon";

revoke delete on table "public"."User_asynkuser_user_permissions" from "authenticated";

revoke insert on table "public"."User_asynkuser_user_permissions" from "authenticated";

revoke references on table "public"."User_asynkuser_user_permissions" from "authenticated";

revoke select on table "public"."User_asynkuser_user_permissions" from "authenticated";

revoke trigger on table "public"."User_asynkuser_user_permissions" from "authenticated";

revoke truncate on table "public"."User_asynkuser_user_permissions" from "authenticated";

revoke update on table "public"."User_asynkuser_user_permissions" from "authenticated";

revoke delete on table "public"."User_asynkuser_user_permissions" from "service_role";

revoke insert on table "public"."User_asynkuser_user_permissions" from "service_role";

revoke references on table "public"."User_asynkuser_user_permissions" from "service_role";

revoke select on table "public"."User_asynkuser_user_permissions" from "service_role";

revoke trigger on table "public"."User_asynkuser_user_permissions" from "service_role";

revoke truncate on table "public"."User_asynkuser_user_permissions" from "service_role";

revoke update on table "public"."User_asynkuser_user_permissions" from "service_role";

revoke delete on table "public"."auth_group" from "anon";

revoke insert on table "public"."auth_group" from "anon";

revoke references on table "public"."auth_group" from "anon";

revoke select on table "public"."auth_group" from "anon";

revoke trigger on table "public"."auth_group" from "anon";

revoke truncate on table "public"."auth_group" from "anon";

revoke update on table "public"."auth_group" from "anon";

revoke delete on table "public"."auth_group" from "authenticated";

revoke insert on table "public"."auth_group" from "authenticated";

revoke references on table "public"."auth_group" from "authenticated";

revoke select on table "public"."auth_group" from "authenticated";

revoke trigger on table "public"."auth_group" from "authenticated";

revoke truncate on table "public"."auth_group" from "authenticated";

revoke update on table "public"."auth_group" from "authenticated";

revoke delete on table "public"."auth_group" from "service_role";

revoke insert on table "public"."auth_group" from "service_role";

revoke references on table "public"."auth_group" from "service_role";

revoke select on table "public"."auth_group" from "service_role";

revoke trigger on table "public"."auth_group" from "service_role";

revoke truncate on table "public"."auth_group" from "service_role";

revoke update on table "public"."auth_group" from "service_role";

revoke delete on table "public"."auth_group_permissions" from "anon";

revoke insert on table "public"."auth_group_permissions" from "anon";

revoke references on table "public"."auth_group_permissions" from "anon";

revoke select on table "public"."auth_group_permissions" from "anon";

revoke trigger on table "public"."auth_group_permissions" from "anon";

revoke truncate on table "public"."auth_group_permissions" from "anon";

revoke update on table "public"."auth_group_permissions" from "anon";

revoke delete on table "public"."auth_group_permissions" from "authenticated";

revoke insert on table "public"."auth_group_permissions" from "authenticated";

revoke references on table "public"."auth_group_permissions" from "authenticated";

revoke select on table "public"."auth_group_permissions" from "authenticated";

revoke trigger on table "public"."auth_group_permissions" from "authenticated";

revoke truncate on table "public"."auth_group_permissions" from "authenticated";

revoke update on table "public"."auth_group_permissions" from "authenticated";

revoke delete on table "public"."auth_group_permissions" from "service_role";

revoke insert on table "public"."auth_group_permissions" from "service_role";

revoke references on table "public"."auth_group_permissions" from "service_role";

revoke select on table "public"."auth_group_permissions" from "service_role";

revoke trigger on table "public"."auth_group_permissions" from "service_role";

revoke truncate on table "public"."auth_group_permissions" from "service_role";

revoke update on table "public"."auth_group_permissions" from "service_role";

revoke delete on table "public"."auth_permission" from "anon";

revoke insert on table "public"."auth_permission" from "anon";

revoke references on table "public"."auth_permission" from "anon";

revoke select on table "public"."auth_permission" from "anon";

revoke trigger on table "public"."auth_permission" from "anon";

revoke truncate on table "public"."auth_permission" from "anon";

revoke update on table "public"."auth_permission" from "anon";

revoke delete on table "public"."auth_permission" from "authenticated";

revoke insert on table "public"."auth_permission" from "authenticated";

revoke references on table "public"."auth_permission" from "authenticated";

revoke select on table "public"."auth_permission" from "authenticated";

revoke trigger on table "public"."auth_permission" from "authenticated";

revoke truncate on table "public"."auth_permission" from "authenticated";

revoke update on table "public"."auth_permission" from "authenticated";

revoke delete on table "public"."auth_permission" from "service_role";

revoke insert on table "public"."auth_permission" from "service_role";

revoke references on table "public"."auth_permission" from "service_role";

revoke select on table "public"."auth_permission" from "service_role";

revoke trigger on table "public"."auth_permission" from "service_role";

revoke truncate on table "public"."auth_permission" from "service_role";

revoke update on table "public"."auth_permission" from "service_role";

revoke delete on table "public"."django_admin_log" from "anon";

revoke insert on table "public"."django_admin_log" from "anon";

revoke references on table "public"."django_admin_log" from "anon";

revoke select on table "public"."django_admin_log" from "anon";

revoke trigger on table "public"."django_admin_log" from "anon";

revoke truncate on table "public"."django_admin_log" from "anon";

revoke update on table "public"."django_admin_log" from "anon";

revoke delete on table "public"."django_admin_log" from "authenticated";

revoke insert on table "public"."django_admin_log" from "authenticated";

revoke references on table "public"."django_admin_log" from "authenticated";

revoke select on table "public"."django_admin_log" from "authenticated";

revoke trigger on table "public"."django_admin_log" from "authenticated";

revoke truncate on table "public"."django_admin_log" from "authenticated";

revoke update on table "public"."django_admin_log" from "authenticated";

revoke delete on table "public"."django_admin_log" from "service_role";

revoke insert on table "public"."django_admin_log" from "service_role";

revoke references on table "public"."django_admin_log" from "service_role";

revoke select on table "public"."django_admin_log" from "service_role";

revoke trigger on table "public"."django_admin_log" from "service_role";

revoke truncate on table "public"."django_admin_log" from "service_role";

revoke update on table "public"."django_admin_log" from "service_role";

revoke delete on table "public"."django_content_type" from "anon";

revoke insert on table "public"."django_content_type" from "anon";

revoke references on table "public"."django_content_type" from "anon";

revoke select on table "public"."django_content_type" from "anon";

revoke trigger on table "public"."django_content_type" from "anon";

revoke truncate on table "public"."django_content_type" from "anon";

revoke update on table "public"."django_content_type" from "anon";

revoke delete on table "public"."django_content_type" from "authenticated";

revoke insert on table "public"."django_content_type" from "authenticated";

revoke references on table "public"."django_content_type" from "authenticated";

revoke select on table "public"."django_content_type" from "authenticated";

revoke trigger on table "public"."django_content_type" from "authenticated";

revoke truncate on table "public"."django_content_type" from "authenticated";

revoke update on table "public"."django_content_type" from "authenticated";

revoke delete on table "public"."django_content_type" from "service_role";

revoke insert on table "public"."django_content_type" from "service_role";

revoke references on table "public"."django_content_type" from "service_role";

revoke select on table "public"."django_content_type" from "service_role";

revoke trigger on table "public"."django_content_type" from "service_role";

revoke truncate on table "public"."django_content_type" from "service_role";

revoke update on table "public"."django_content_type" from "service_role";

revoke delete on table "public"."django_migrations" from "anon";

revoke insert on table "public"."django_migrations" from "anon";

revoke references on table "public"."django_migrations" from "anon";

revoke select on table "public"."django_migrations" from "anon";

revoke trigger on table "public"."django_migrations" from "anon";

revoke truncate on table "public"."django_migrations" from "anon";

revoke update on table "public"."django_migrations" from "anon";

revoke delete on table "public"."django_migrations" from "authenticated";

revoke insert on table "public"."django_migrations" from "authenticated";

revoke references on table "public"."django_migrations" from "authenticated";

revoke select on table "public"."django_migrations" from "authenticated";

revoke trigger on table "public"."django_migrations" from "authenticated";

revoke truncate on table "public"."django_migrations" from "authenticated";

revoke update on table "public"."django_migrations" from "authenticated";

revoke delete on table "public"."django_migrations" from "service_role";

revoke insert on table "public"."django_migrations" from "service_role";

revoke references on table "public"."django_migrations" from "service_role";

revoke select on table "public"."django_migrations" from "service_role";

revoke trigger on table "public"."django_migrations" from "service_role";

revoke truncate on table "public"."django_migrations" from "service_role";

revoke update on table "public"."django_migrations" from "service_role";

revoke delete on table "public"."django_q_ormq" from "anon";

revoke insert on table "public"."django_q_ormq" from "anon";

revoke references on table "public"."django_q_ormq" from "anon";

revoke select on table "public"."django_q_ormq" from "anon";

revoke trigger on table "public"."django_q_ormq" from "anon";

revoke truncate on table "public"."django_q_ormq" from "anon";

revoke update on table "public"."django_q_ormq" from "anon";

revoke delete on table "public"."django_q_ormq" from "authenticated";

revoke insert on table "public"."django_q_ormq" from "authenticated";

revoke references on table "public"."django_q_ormq" from "authenticated";

revoke select on table "public"."django_q_ormq" from "authenticated";

revoke trigger on table "public"."django_q_ormq" from "authenticated";

revoke truncate on table "public"."django_q_ormq" from "authenticated";

revoke update on table "public"."django_q_ormq" from "authenticated";

revoke delete on table "public"."django_q_ormq" from "service_role";

revoke insert on table "public"."django_q_ormq" from "service_role";

revoke references on table "public"."django_q_ormq" from "service_role";

revoke select on table "public"."django_q_ormq" from "service_role";

revoke trigger on table "public"."django_q_ormq" from "service_role";

revoke truncate on table "public"."django_q_ormq" from "service_role";

revoke update on table "public"."django_q_ormq" from "service_role";

revoke delete on table "public"."django_q_schedule" from "anon";

revoke insert on table "public"."django_q_schedule" from "anon";

revoke references on table "public"."django_q_schedule" from "anon";

revoke select on table "public"."django_q_schedule" from "anon";

revoke trigger on table "public"."django_q_schedule" from "anon";

revoke truncate on table "public"."django_q_schedule" from "anon";

revoke update on table "public"."django_q_schedule" from "anon";

revoke delete on table "public"."django_q_schedule" from "authenticated";

revoke insert on table "public"."django_q_schedule" from "authenticated";

revoke references on table "public"."django_q_schedule" from "authenticated";

revoke select on table "public"."django_q_schedule" from "authenticated";

revoke trigger on table "public"."django_q_schedule" from "authenticated";

revoke truncate on table "public"."django_q_schedule" from "authenticated";

revoke update on table "public"."django_q_schedule" from "authenticated";

revoke delete on table "public"."django_q_schedule" from "service_role";

revoke insert on table "public"."django_q_schedule" from "service_role";

revoke references on table "public"."django_q_schedule" from "service_role";

revoke select on table "public"."django_q_schedule" from "service_role";

revoke trigger on table "public"."django_q_schedule" from "service_role";

revoke truncate on table "public"."django_q_schedule" from "service_role";

revoke update on table "public"."django_q_schedule" from "service_role";

revoke delete on table "public"."django_q_task" from "anon";

revoke insert on table "public"."django_q_task" from "anon";

revoke references on table "public"."django_q_task" from "anon";

revoke select on table "public"."django_q_task" from "anon";

revoke trigger on table "public"."django_q_task" from "anon";

revoke truncate on table "public"."django_q_task" from "anon";

revoke update on table "public"."django_q_task" from "anon";

revoke delete on table "public"."django_q_task" from "authenticated";

revoke insert on table "public"."django_q_task" from "authenticated";

revoke references on table "public"."django_q_task" from "authenticated";

revoke select on table "public"."django_q_task" from "authenticated";

revoke trigger on table "public"."django_q_task" from "authenticated";

revoke truncate on table "public"."django_q_task" from "authenticated";

revoke update on table "public"."django_q_task" from "authenticated";

revoke delete on table "public"."django_q_task" from "service_role";

revoke insert on table "public"."django_q_task" from "service_role";

revoke references on table "public"."django_q_task" from "service_role";

revoke select on table "public"."django_q_task" from "service_role";

revoke trigger on table "public"."django_q_task" from "service_role";

revoke truncate on table "public"."django_q_task" from "service_role";

revoke update on table "public"."django_q_task" from "service_role";

revoke delete on table "public"."django_session" from "anon";

revoke insert on table "public"."django_session" from "anon";

revoke references on table "public"."django_session" from "anon";

revoke select on table "public"."django_session" from "anon";

revoke trigger on table "public"."django_session" from "anon";

revoke truncate on table "public"."django_session" from "anon";

revoke update on table "public"."django_session" from "anon";

revoke delete on table "public"."django_session" from "authenticated";

revoke insert on table "public"."django_session" from "authenticated";

revoke references on table "public"."django_session" from "authenticated";

revoke select on table "public"."django_session" from "authenticated";

revoke trigger on table "public"."django_session" from "authenticated";

revoke truncate on table "public"."django_session" from "authenticated";

revoke update on table "public"."django_session" from "authenticated";

revoke delete on table "public"."django_session" from "service_role";

revoke insert on table "public"."django_session" from "service_role";

revoke references on table "public"."django_session" from "service_role";

revoke select on table "public"."django_session" from "service_role";

revoke trigger on table "public"."django_session" from "service_role";

revoke truncate on table "public"."django_session" from "service_role";

revoke update on table "public"."django_session" from "service_role";


